
---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?
For now, I believe I have a lot to improve.

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?

# Reflect on writing more generally

- What principles of composition discussed today did you find most useful?
Avoiding useless jargon.
Writing in active voice.

- If you were going to formulate your own writing rules, what would they be?

# Commit your reflections to writing

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.

Practise more writing/ scientific writing. 
Learn the difference in words used e.g affect and effect.
Write clearly so that the target audience understands the message that I am trying to convey.
Improve my grammar which will result in less use of the grammar correcting tools.
Read more on the guide recommended
