---
title: "WritingExercise02"
---

# Instructions

Each of the writing samples below violates at least one of Strunk and White’s Principles of Composition. Read the samples critically, and edit to improve them. Remember to make a commit to save your changes when you are done. 

# Writing Samples

## Principle: use the active voice

To understand the metabolic pathways in bacteria we anaylsed it.

## Put statements in positive form.

Glucose metabolising bacteria is vital for fermentation.

## Use definite, specific, concrete language.

Algae can be useful for biofuel production.

## Omit needless words.

Citric acid production can be enhanced by engineering Aspergillus niger's metabolic pathways.

## Express coordinate ideas in similar form.

Microbes are used to produce a range of fermented foods such as, yeast,bacillus, natto, cheese, fermented vegetables, pickles, coffee and chocolate. 

## Keep related words together.

Polythylene (PET) can be degraded by the Ideonella sakaiensis microbe using PETase enzyme.


## In summaries, keep to one tense.

The engineered *E. coli* strain was grown in a 5 L bioreactor for 24 hours. This steadily decreased the glucose concentration and optical density increased from 0.2 to 8.4. Following this, centrifugation was used to harvest the culture and recombinant enzyme was purified by affinity chromatography.

The purified enzyme showed a specific activity of 42 U/mg and is suitable for use in the subsequent biocatalytic process.

## Place the emphatic words of a sentence at the end.

Streptomyces produce antibiotics, and genomic data suggests that any given species can potentially produce a wide variety of them. 

